theme: jekyll-theme-minimal
title: Vikas Patil
description: Cybersecurity Portfolio | Blue Team & ML
logo: https://avatars.githubusercontent.com/u/vikas-6325?v=4
show_downloads: false
google_analytics:
